import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'zh' | 'en' | 'ja' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    'nav.explore': '探索',
    'nav.smartSearch': '智能推荐',
    'nav.login': '登录',
    'nav.register': '注册',
    'nav.profile': '个人中心',
    'nav.admin': '后台管理',
    'nav.logout': '退出登录',
    'search.placeholder': '搜索AI工具...',
    'brand.name': 'AI导航',

    'hero.badge': '发现 {count} 精选AI工具',
    'hero.h1': '探索 AI 工具的无限可能',
    'hero.desc': '汇集全网优质 AI 工具，覆盖对话、绘画、视频、音频、写作、编程等多个领域',
    'hero.placeholder': '搜索AI工具名称、功能或分类...',
    'hero.searchButton': '搜索',
    'hero.smartCta': '不知道选什么？试试 AI 智能推荐',
    'hero.popular': '热门：',
    'hero.stats.tools': 'AI工具',
    'hero.stats.categories': '分类',
    'hero.stats.daily': '每日更新',

    'hot.badge': '热门推荐',
    'hot.title': '最受欢迎的 AI 工具',
    'hot.desc': '精选用户评价最高、使用最多的AI工具，助你快速找到最适合的解决方案',
    'hot.prev': '上一页',
    'hot.next': '下一页',
    'hot.total': '共 {count} 个工具',
    'hot.empty': '该筛选条件下暂无热门工具',

    'cat.badge': '全部分类',
    'cat.title': '按分类浏览 AI 工具',
    'cat.desc': '覆盖对话、绘画、视频、音频、写作、编程等多个领域',
    'cat.viewMore': '查看更多',
    'cat.emptyTools': '该分类暂无工具',
    'cat.noData': '暂无分类数据',
    'cat.notFound': '分类不存在',
    'cat.notFoundDesc': '请检查链接是否正确',
    'cat.count': '共 {count} 个工具',
    'cat.emptyFilter': '该筛选条件下暂无工具，请尝试其他筛选',

    'oscar.badge': 'Oscar 排行榜',
    'oscar.title': 'AI 工具 Oscar 排名',
    'oscar.desc': '综合浏览量、评分和评价数等维度，为每个类别评选出最受欢迎的Top 3工具',
    'oscar.viewAll': '查看全部',
    'oscar.empty': '暂无排名数据',

    'news.title': 'AI 资讯',
    'news.live': '实时更新',
    'news.empty': '暂无新闻资讯',
    'news.more': '查看更多资讯',

    'card.hot': '热门',
    'card.featured': '⭐ 精选',

    'footer.tagline': '发现最好用的AI工具，提升您的工作效率',
    'footer.categories': '工具分类',
    'footer.quickLinks': '快速链接',
    'footer.home': '首页',
    'footer.submit': '提交工具',
    'footer.allCategories': '全部分类',
    'footer.feedback': '反馈建议',
    'footer.contact': '联系方式',

    'result.title': '搜索结果：',
    'result.count': '共找到 {count} 个结果',
    'result.notFound': '未找到相关工具',
    'result.notFoundDesc': '尝试更换筛选条件或使用不同的关键词',

    'explore.badge': '高级筛选',
    'explore.title': '探索',
    'explore.titleAccent': 'AI工具库',
    'explore.desc': '从 {count} 个AI工具中，通过多维度筛选找到最适合你的工具',
    'explore.placeholder': '搜索工具名称、描述或标签...',
    'explore.clear': '清除',
    'explore.allCategories': '全部分类',
    'explore.results': '搜索结果',
    'explore.count': '{count} 个工具',
    'explore.noMatch': '未找到匹配的工具',
    'explore.noMatchDesc': '尝试调整筛选条件或更换搜索关键词',
    'explore.clearAll': '清除所有筛选',
    'explore.hotTags': '热门标签',
    'filter.title': '智能筛选',
    'filter.conditions': '{count} 个条件',
    'filter.found': '找到 {count} 个',
    'filter.filtered': '已筛选',
    'filter.clearAll': '清除全部',
    'filter.collapse': '收起高级筛选',
    'filter.expand': '展开高级筛选（分类、场景、平台、厂商）',
    'filter.group.access': '访问方式',
    'filter.group.pricing': '价格',
    'filter.group.category': '分类',
    'filter.group.features': '特性',
    'filter.group.usecase': '应用场景',
    'filter.group.platform': '平台',
    'filter.group.provider': '厂商',
    'filter.opt.no-vpn': '国内直连',
    'filter.opt.vpn-required': '需要梯子',
    'filter.opt.free': '完全免费',
    'filter.opt.freemium': '免费额度',
    'filter.opt.paid': '付费',
    'filter.opt.chat': '对话',
    'filter.opt.image': '绘画',
    'filter.opt.video': '视频',
    'filter.opt.audio': '音频',
    'filter.opt.music': '音乐',
    'filter.opt.writing': '写作',
    'filter.opt.code': '编程',
    'filter.opt.opensource': '开源',
    'filter.opt.chinese': '国产',
    'filter.opt.chinese-friendly': '中文友好',
    'filter.opt.enterprise': '企业版',
    'filter.opt.api': 'API接口',
    'filter.opt.multimodal': '多模态',
    'filter.opt.marketing': '营销',
    'filter.opt.education': '教育',
    'filter.opt.design': '设计',
    'filter.opt.productivity': '效率',
    'filter.opt.research': '研究',
    'filter.opt.health': '健康',
    'filter.opt.finance': '金融',
    'filter.opt.web': '网页版',
    'filter.opt.mobile': '移动端',
    'filter.opt.plugin': '插件',
    'filter.opt.openai': 'OpenAI',
    'filter.opt.google': 'Google',
    'filter.opt.meta': 'Meta',
    'filter.opt.microsoft': '微软',
    'filter.opt.baidu': '百度',
    'filter.opt.alibaba': '阿里',
    'filter.opt.tencent': '腾讯',
    'filter.opt.bytedance': '字节',
    'filter.opt.xunfei': '讯飞',

    'auth.loginTitle': '登录',
    'auth.loginDesc': '登录您的账户以使用完整功能',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.noAccount': '还没有账户？',
    'auth.goRegister': '立即注册',
    'auth.loginBtn': '登录',
    'auth.loginFailed': '登录失败',
    'auth.loginSuccess': '登录成功',
    'auth.welcomeBack': '欢迎回来！',
    'auth.registerTitle': '注册账户',
    'auth.registerDesc': '创建一个新账户以收藏和评论AI工具',
    'auth.confirmPassword': '确认密码',
    'auth.registerBtn': '注册',
    'auth.haveAccount': '已有账户？',
    'auth.goLogin': '立即登录',
    'auth.pwdMismatch': '密码不匹配',
    'auth.pwdMismatchDesc': '请确保两次输入的密码相同',
    'auth.pwdShort': '密码太短',
    'auth.pwdShortDesc': '密码至少需要6个字符',
    'auth.registerFailed': '注册失败',
    'auth.registerSuccess': '注册成功',
    'auth.welcome': '欢迎加入！',
    'detail.loginFirst': '请先登录',
    'detail.favAdded': '已添加收藏',
    'detail.favRemoved': '已取消收藏',
    'detail.commentEmpty': '请输入评论内容',
    'detail.commentSuccess': '评论发布成功',
    'detail.commentFailed': '评论失败',
    'detail.notFound': '工具不存在',
    'detail.backHome': '返回首页',
    'detail.hot': '热门',
    'detail.featured': '精选',
    'detail.reviews': '{count} 条评价',
    'detail.views': '{count} 次浏览',
    'detail.added': '收录于 {date}',
    'detail.visit': '访问官网',
    'detail.favorited': '已收藏',
    'detail.favorite': '收藏',
    'detail.details': '详细介绍',
    'detail.quickInfo': '快速信息',
    'detail.website': '官方网站',
    'detail.category': '分类',
    'detail.viewCount': '浏览量',
    'detail.times': '{count} 次',
    'detail.comments': '用户评价 ({count})',
    'detail.rating': '评分：',
    'detail.commentPlaceholder': '分享你的使用体验...',
    'detail.submitComment': '发表评论',
    'detail.loginToComment': '登录后可以发表评论',
    'detail.goLogin': '去登录',
    'detail.anonymous': '匿名用户',
    'detail.noComments': '暂无评论，来发表第一条评论吧',
    'profile.joined': '加入于 {date}',
    'profile.favorites': '我的收藏 ({count})',
    'profile.comments': '我的评论 ({count})',
    'profile.noFavorites': '暂无收藏的工具',
    'profile.noComments': '暂无评论',
    'smart.badge': 'AI智能推荐',
    'smart.title1': '描述您的需求，',
    'smart.title2': 'AI为您推荐',
    'smart.desc': '不知道该用什么AI工具？告诉我您想做什么，AI将从{count}工具中为您精选最合适的推荐',
    'smart.f1': '智能理解需求',
    'smart.f2': '秒级推荐',
    'smart.f3': '精准匹配',
    'smart.placeholder': '描述您的需求，AI将为您推荐最合适的工具...\n例如：我想用AI生成营销文案和图片',
    'smart.hint': '按 Enter 发送，Shift + Enter 换行',
    'smart.analyzing': 'AI分析中...',
    'smart.submit': '智能推荐',
    'smart.examples': '试试这些例子：',
    'smart.loading': 'AI正在分析您的需求...',
    'smart.loadingDesc': '正在从{count}工具中筛选最匹配的推荐',
    'smart.found': '为您找到 {count} 个推荐',
    'smart.rec': '推荐 {index}',
    'smart.retry': '重新描述需求',
    'smart.noResult': '未找到匹配的工具，请尝试换一种方式描述您的需求',
    'smart.searchAgain': '重新搜索',
    'smart.emptyInput': '请输入您的需求描述',
    'smart.error': '推荐服务暂时不可用，请稍后重试',
    'smart.ex1': '我想做短视频，需要AI帮我生成脚本、配音和剪辑',
    'smart.ex2': '帮我找一些免费的AI绘画工具，最好不需要翻墙',
    'smart.ex3': '我是程序员，想提高编程效率，有什么AI工具推荐？',
    'smart.ex4': '我需要AI帮我处理Excel数据和生成报告',
    'news.justNow': '刚刚',
    'oauth.loadFailed': '授权请求无法加载',
    'oauth.loading': '正在加载授权请求…',
    'oauth.connect': '将 {app} 连接到你的账户',
    'oauth.desc': '授权后，{app} 可以以你的身份访问本站的工具数据与收藏。',
    'oauth.approve': '同意授权',
    'oauth.deny': '拒绝',
    'oauth.thisApp': '该应用',

    'category.ai-chat': 'AI对话',
    'category.ai-image': 'AI绘画',
    'category.ai-video': 'AI视频',
    'category.ai-audio': 'AI音频',
    'category.ai-writing': 'AI写作',
    'category.ai-code': '代码生成',
    'category.ai-education': 'AI教育',
    'category.ai-music': 'AI音乐',
    'category.ai-health': 'AI健康',
    'category.ai-life': 'AI生活',
    'category.ai-finance': 'AI金融',
    'category.ai-business': 'AI商业',
    'category.ai-design': 'AI设计',
    'category.ai-architecture': 'AI建筑',
    'category.ai-agent': 'AI Agent',
    'category.ai-other': '其他',
    'catdesc.ai-agent': "热门AI智能体与自动化Agent合集",
    'catdesc.ai-audio': "语音合成、音乐生成、音频处理",
    'catdesc.ai-business': "企业管理、营销推广、数据分析",
    'catdesc.ai-chat': "智能对话助手，支持问答、写作、编程等多种场景",
    'catdesc.ai-code': "代码生成、代码补全、编程助手",
    'catdesc.ai-design': "UI设计、平面设计、创意工具",
    'catdesc.ai-education': "智能学习、在线教育、知识问答",
    'catdesc.ai-finance': "金融分析、投资建议、理财工具",
    'catdesc.ai-health': "健康管理、医疗咨询、健身指导",
    'catdesc.ai-image': "AI图像生成与编辑工具，创作精美图片",
    'catdesc.ai-life': "日常生活助手、效率工具",
    'catdesc.ai-music': "音乐创作、歌曲生成、编曲工具",
    'catdesc.ai-video': "AI视频生成、编辑和特效处理",
    'catdesc.ai-writing': "文案创作、内容生成、文本优化",
  },
  en: {
    'nav.explore': 'Explore',
    'nav.smartSearch': 'Smart Search',
    'nav.login': 'Login',
    'nav.register': 'Sign Up',
    'nav.profile': 'Profile',
    'nav.admin': 'Admin',
    'nav.logout': 'Logout',
    'search.placeholder': 'Search AI tools...',
    'brand.name': 'AI Directory',

    'hero.badge': 'Discover {count} curated AI tools',
    'hero.h1': 'Explore the Possibilities of AI Tools',
    'hero.desc': 'A curated collection of AI tools for chat, art, video, audio, writing, coding and more',
    'hero.placeholder': 'Search tools by name, feature or category...',
    'hero.searchButton': 'Search',
    'hero.smartCta': 'Not sure what to pick? Try AI recommendations',
    'hero.popular': 'Popular:',
    'hero.stats.tools': 'AI Tools',
    'hero.stats.categories': 'Categories',
    'hero.stats.daily': 'Daily Updates',

    'hot.badge': 'Trending',
    'hot.title': 'Most Popular AI Tools',
    'hot.desc': 'Top-rated and most-used AI tools, hand-picked to help you find the right solution fast',
    'hot.prev': 'Previous',
    'hot.next': 'Next',
    'hot.total': '{count} tools',
    'hot.empty': 'No tools match the current filters',

    'cat.badge': 'All Categories',
    'cat.title': 'Browse AI Tools by Category',
    'cat.desc': 'Covering chat, art, video, audio, writing, coding and many more fields',
    'cat.viewMore': 'View more',
    'cat.emptyTools': 'No tools in this category yet',
    'cat.noData': 'No categories available',
    'cat.notFound': 'Category not found',
    'cat.notFoundDesc': 'Please check that the link is correct',
    'cat.count': '{count} tools',
    'cat.emptyFilter': 'No tools match these filters, try different ones',

    'oscar.badge': 'Oscar Rankings',
    'oscar.title': 'AI Tools Oscar Rankings',
    'oscar.desc': 'Top 3 tools per category, scored by views, ratings and number of reviews',
    'oscar.viewAll': 'View all',
    'oscar.empty': 'No ranking data',

    'news.title': 'AI News',
    'news.live': 'Live',
    'news.empty': 'No news yet',
    'news.more': 'More news',

    'card.hot': 'Hot',
    'card.featured': '⭐ Featured',

    'footer.tagline': 'Discover the best AI tools and boost your productivity',
    'footer.categories': 'Categories',
    'footer.quickLinks': 'Quick Links',
    'footer.home': 'Home',
    'footer.submit': 'Submit a Tool',
    'footer.allCategories': 'All Categories',
    'footer.feedback': 'Feedback',
    'footer.contact': 'Contact',

    'result.title': 'Results for: ',
    'result.count': '{count} results found',
    'result.notFound': 'No matching tools found',
    'result.notFoundDesc': 'Try different filters or another keyword',

    'explore.badge': 'Advanced Filters',
    'explore.title': 'Explore the',
    'explore.titleAccent': 'AI Tool Library',
    'explore.desc': 'Filter across {count} AI tools to find the perfect fit',
    'explore.placeholder': 'Search by name, description or tag...',
    'explore.clear': 'Clear',
    'explore.allCategories': 'All Categories',
    'explore.results': 'Results',
    'explore.count': '{count} tools',
    'explore.noMatch': 'No matching tools',
    'explore.noMatchDesc': 'Try adjusting the filters or changing your keyword',
    'explore.clearAll': 'Clear all filters',
    'explore.hotTags': 'Popular Tags',
    'filter.title': 'Smart Filters',
    'filter.conditions': '{count} active',
    'filter.found': '{count} found',
    'filter.filtered': 'Filtered',
    'filter.clearAll': 'Clear all',
    'filter.collapse': 'Hide advanced filters',
    'filter.expand': 'Show advanced filters (category, use case, platform, vendor)',
    'filter.group.access': 'Access',
    'filter.group.pricing': 'Pricing',
    'filter.group.category': 'Category',
    'filter.group.features': 'Features',
    'filter.group.usecase': 'Use Case',
    'filter.group.platform': 'Platform',
    'filter.group.provider': 'Vendor',
    'filter.opt.no-vpn': 'Direct Access',
    'filter.opt.vpn-required': 'VPN Required',
    'filter.opt.free': 'Free',
    'filter.opt.freemium': 'Freemium',
    'filter.opt.paid': 'Paid',
    'filter.opt.chat': 'Chat',
    'filter.opt.image': 'Image',
    'filter.opt.video': 'Video',
    'filter.opt.audio': 'Audio',
    'filter.opt.music': 'Music',
    'filter.opt.writing': 'Writing',
    'filter.opt.code': 'Coding',
    'filter.opt.opensource': 'Open Source',
    'filter.opt.chinese': 'Made in China',
    'filter.opt.chinese-friendly': 'Chinese Friendly',
    'filter.opt.enterprise': 'Enterprise',
    'filter.opt.api': 'API',
    'filter.opt.multimodal': 'Multimodal',
    'filter.opt.marketing': 'Marketing',
    'filter.opt.education': 'Education',
    'filter.opt.design': 'Design',
    'filter.opt.productivity': 'Productivity',
    'filter.opt.research': 'Research',
    'filter.opt.health': 'Health',
    'filter.opt.finance': 'Finance',
    'filter.opt.web': 'Web',
    'filter.opt.mobile': 'Mobile',
    'filter.opt.plugin': 'Plugin',
    'filter.opt.openai': 'OpenAI',
    'filter.opt.google': 'Google',
    'filter.opt.meta': 'Meta',
    'filter.opt.microsoft': 'Microsoft',
    'filter.opt.baidu': 'Baidu',
    'filter.opt.alibaba': 'Alibaba',
    'filter.opt.tencent': 'Tencent',
    'filter.opt.bytedance': 'ByteDance',
    'filter.opt.xunfei': 'iFlytek',

    'auth.loginTitle': 'Login',
    'auth.loginDesc': 'Sign in to your account to unlock all features',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.noAccount': "Don't have an account?",
    'auth.goRegister': 'Sign up now',
    'auth.loginBtn': 'Sign in',
    'auth.loginFailed': 'Sign-in failed',
    'auth.loginSuccess': 'Signed in',
    'auth.welcomeBack': 'Welcome back!',
    'auth.registerTitle': 'Create account',
    'auth.registerDesc': 'Create an account to save and review AI tools',
    'auth.confirmPassword': 'Confirm password',
    'auth.registerBtn': 'Sign up',
    'auth.haveAccount': 'Already have an account?',
    'auth.goLogin': 'Sign in',
    'auth.pwdMismatch': 'Passwords do not match',
    'auth.pwdMismatchDesc': 'Please make sure both passwords are identical',
    'auth.pwdShort': 'Password too short',
    'auth.pwdShortDesc': 'Password must be at least 6 characters',
    'auth.registerFailed': 'Sign-up failed',
    'auth.registerSuccess': 'Account created',
    'auth.welcome': 'Welcome aboard!',
    'detail.loginFirst': 'Please sign in first',
    'detail.favAdded': 'Added to favorites',
    'detail.favRemoved': 'Removed from favorites',
    'detail.commentEmpty': 'Please write a comment',
    'detail.commentSuccess': 'Comment posted',
    'detail.commentFailed': 'Failed to post comment',
    'detail.notFound': 'Tool not found',
    'detail.backHome': 'Back to home',
    'detail.hot': 'Hot',
    'detail.featured': 'Featured',
    'detail.reviews': '{count} reviews',
    'detail.views': '{count} views',
    'detail.added': 'Added {date}',
    'detail.visit': 'Visit website',
    'detail.favorited': 'Saved',
    'detail.favorite': 'Save',
    'detail.details': 'Details',
    'detail.quickInfo': 'Quick info',
    'detail.website': 'Website',
    'detail.category': 'Category',
    'detail.viewCount': 'Views',
    'detail.times': '{count}',
    'detail.comments': 'Reviews ({count})',
    'detail.rating': 'Rating:',
    'detail.commentPlaceholder': 'Share your experience...',
    'detail.submitComment': 'Post comment',
    'detail.loginToComment': 'Sign in to leave a comment',
    'detail.goLogin': 'Sign in',
    'detail.anonymous': 'Anonymous',
    'detail.noComments': 'No comments yet — be the first to share',
    'profile.joined': 'Joined {date}',
    'profile.favorites': 'My favorites ({count})',
    'profile.comments': 'My comments ({count})',
    'profile.noFavorites': 'No saved tools yet',
    'profile.noComments': 'No comments yet',
    'smart.badge': 'AI Recommendations',
    'smart.title1': 'Describe what you need,',
    'smart.title2': 'AI finds the tool',
    'smart.desc': 'Not sure which AI tool to use? Tell us what you want to do and AI will pick the best matches from {count} tools',
    'smart.f1': 'Understands intent',
    'smart.f2': 'Instant results',
    'smart.f3': 'Precise matching',
    'smart.placeholder': 'Describe your needs and AI will recommend the best tools...\ne.g. I want to generate marketing copy and images with AI',
    'smart.hint': 'Press Enter to send, Shift + Enter for a new line',
    'smart.analyzing': 'Analyzing...',
    'smart.submit': 'Recommend',
    'smart.examples': 'Try these examples:',
    'smart.loading': 'AI is analyzing your request...',
    'smart.loadingDesc': 'Screening the best matches from {count} tools',
    'smart.found': '{count} recommendations for you',
    'smart.rec': 'Pick {index}',
    'smart.retry': 'Describe again',
    'smart.noResult': 'No matching tools found. Try describing your needs differently.',
    'smart.searchAgain': 'Search again',
    'smart.emptyInput': 'Please describe what you need',
    'smart.error': 'The recommendation service is unavailable, please try again later',
    'smart.ex1': 'I make short videos and need AI for scripts, voiceover and editing',
    'smart.ex2': 'Find me free AI image generators that work without a VPN',
    'smart.ex3': 'I\'m a developer — which AI tools boost coding productivity?',
    'smart.ex4': 'I need AI to process Excel data and generate reports',
    'news.justNow': 'Just now',
    'oauth.loadFailed': 'Could not load the authorization request',
    'oauth.loading': 'Loading authorization request…',
    'oauth.connect': 'Connect {app} to your account',
    'oauth.desc': 'Once approved, {app} can access tool data and your favorites on your behalf.',
    'oauth.approve': 'Approve',
    'oauth.deny': 'Deny',
    'oauth.thisApp': 'this app',

    'category.ai-chat': 'AI Chat',
    'category.ai-image': 'AI Image',
    'category.ai-video': 'AI Video',
    'category.ai-audio': 'AI Audio',
    'category.ai-writing': 'AI Writing',
    'category.ai-code': 'Code Generation',
    'category.ai-education': 'AI Education',
    'category.ai-music': 'AI Music',
    'category.ai-health': 'AI Health',
    'category.ai-life': 'AI Lifestyle',
    'category.ai-finance': 'AI Finance',
    'category.ai-business': 'AI Business',
    'category.ai-design': 'AI Design',
    'category.ai-architecture': 'AI Architecture',
    'category.ai-agent': 'AI Agent',
    'category.ai-other': 'Other',
    'catdesc.ai-agent': "Top AI agents and automation agents",
    'catdesc.ai-audio': "Speech synthesis, music generation, audio processing",
    'catdesc.ai-business': "Business management, marketing, data analytics",
    'catdesc.ai-chat': "Smart chat assistants for Q&A, writing and coding",
    'catdesc.ai-code': "Code generation, completion and programming assistants",
    'catdesc.ai-design': "UI design, graphic design and creative tools",
    'catdesc.ai-education': "Smart learning, online education and knowledge Q&A",
    'catdesc.ai-finance': "Financial analysis, investment advice and money tools",
    'catdesc.ai-health': "Health management, medical advice and fitness guidance",
    'catdesc.ai-image': "AI image generation and editing tools",
    'catdesc.ai-life': "Everyday life assistants and productivity tools",
    'catdesc.ai-music': "Music creation, song generation and arrangement tools",
    'catdesc.ai-video': "AI video generation, editing and visual effects",
    'catdesc.ai-writing': "Copywriting, content generation and text optimization",
  },
  ja: {
    'nav.explore': '探索',
    'nav.smartSearch': 'スマート検索',
    'nav.login': 'ログイン',
    'nav.register': '登録',
    'nav.profile': 'プロフィール',
    'nav.admin': '管理画面',
    'nav.logout': 'ログアウト',
    'search.placeholder': 'AIツールを検索...',
    'brand.name': 'AIナビ',

    'hero.badge': '{count} の厳選AIツールを掲載',
    'hero.h1': 'AIツールの無限の可能性を探索',
    'hero.desc': '対話・画像・動画・音声・ライティング・コーディングなど、優れたAIツールを網羅',
    'hero.placeholder': 'ツール名・機能・カテゴリで検索...',
    'hero.searchButton': '検索',
    'hero.smartCta': '迷ったら？AIスマートおすすめを試す',
    'hero.popular': '人気：',
    'hero.stats.tools': 'AIツール',
    'hero.stats.categories': 'カテゴリ',
    'hero.stats.daily': '毎日更新',

    'hot.badge': '人気のおすすめ',
    'hot.title': '最も人気のAIツール',
    'hot.desc': '評価が高く、利用の多いAIツールを厳選しました',
    'hot.prev': '前へ',
    'hot.next': '次へ',
    'hot.total': '全 {count} 件',
    'hot.empty': 'この条件に一致するツールはありません',

    'cat.badge': '全カテゴリ',
    'cat.title': 'カテゴリ別にAIツールを見る',
    'cat.desc': '対話・画像・動画・音声・ライティング・コーディングなど',
    'cat.viewMore': 'もっと見る',
    'cat.emptyTools': 'このカテゴリにはまだツールがありません',
    'cat.noData': 'カテゴリがありません',
    'cat.notFound': 'カテゴリが存在しません',
    'cat.notFoundDesc': 'リンクをご確認ください',
    'cat.count': '全 {count} 件',
    'cat.emptyFilter': 'この条件に一致するツールはありません',

    'oscar.badge': 'Oscar ランキング',
    'oscar.title': 'AIツール Oscar ランキング',
    'oscar.desc': '閲覧数・評価・レビュー数からカテゴリ別トップ3を選出',
    'oscar.viewAll': 'すべて見る',
    'oscar.empty': 'ランキングデータがありません',

    'news.title': 'AIニュース',
    'news.live': 'リアルタイム',
    'news.empty': 'ニュースはありません',
    'news.more': 'もっと見る',

    'card.hot': '人気',
    'card.featured': '⭐ 厳選',

    'footer.tagline': '最適なAIツールを見つけて生産性を高めましょう',
    'footer.categories': 'カテゴリ',
    'footer.quickLinks': 'クイックリンク',
    'footer.home': 'ホーム',
    'footer.submit': 'ツールを投稿',
    'footer.allCategories': '全カテゴリ',
    'footer.feedback': 'フィードバック',
    'footer.contact': 'お問い合わせ',

    'result.title': '検索結果：',
    'result.count': '{count} 件の結果',
    'result.notFound': '該当するツールが見つかりません',
    'result.notFoundDesc': '条件やキーワードを変えてお試しください',

    'explore.badge': '詳細フィルター',
    'explore.title': '探索',
    'explore.titleAccent': 'AIツールライブラリ',
    'explore.desc': '{count} 件のAIツールから最適なものを絞り込み',
    'explore.placeholder': '名前・説明・タグで検索...',
    'explore.clear': 'クリア',
    'explore.allCategories': '全カテゴリ',
    'explore.results': '検索結果',
    'explore.count': '{count} 件',
    'explore.noMatch': '一致するツールがありません',
    'explore.noMatchDesc': '条件やキーワードを調整してください',
    'explore.clearAll': 'すべてのフィルターをクリア',
    'explore.hotTags': '人気のタグ',
    'filter.title': 'スマートフィルター',
    'filter.conditions': '{count} 件の条件',
    'filter.found': '{count} 件見つかりました',
    'filter.filtered': '絞り込み済み',
    'filter.clearAll': 'すべてクリア',
    'filter.collapse': '詳細フィルターを閉じる',
    'filter.expand': '詳細フィルターを開く（カテゴリ・用途・プラットフォーム・ベンダー）',
    'filter.group.access': 'アクセス',
    'filter.group.pricing': '価格',
    'filter.group.category': 'カテゴリ',
    'filter.group.features': '特徴',
    'filter.group.usecase': '用途',
    'filter.group.platform': 'プラットフォーム',
    'filter.group.provider': 'ベンダー',
    'filter.opt.no-vpn': '直接アクセス',
    'filter.opt.vpn-required': 'VPN必須',
    'filter.opt.free': '完全無料',
    'filter.opt.freemium': '無料枠あり',
    'filter.opt.paid': '有料',
    'filter.opt.chat': 'チャット',
    'filter.opt.image': '画像',
    'filter.opt.video': '動画',
    'filter.opt.audio': '音声',
    'filter.opt.music': '音楽',
    'filter.opt.writing': 'ライティング',
    'filter.opt.code': 'コーディング',
    'filter.opt.opensource': 'オープンソース',
    'filter.opt.chinese': '中国製',
    'filter.opt.chinese-friendly': '中国語対応',
    'filter.opt.enterprise': 'エンタープライズ',
    'filter.opt.api': 'API',
    'filter.opt.multimodal': 'マルチモーダル',
    'filter.opt.marketing': 'マーケティング',
    'filter.opt.education': '教育',
    'filter.opt.design': 'デザイン',
    'filter.opt.productivity': '生産性',
    'filter.opt.research': 'リサーチ',
    'filter.opt.health': 'ヘルス',
    'filter.opt.finance': '金融',
    'filter.opt.web': 'ウェブ',
    'filter.opt.mobile': 'モバイル',
    'filter.opt.plugin': 'プラグイン',
    'filter.opt.openai': 'OpenAI',
    'filter.opt.google': 'Google',
    'filter.opt.meta': 'Meta',
    'filter.opt.microsoft': 'Microsoft',
    'filter.opt.baidu': 'Baidu',
    'filter.opt.alibaba': 'Alibaba',
    'filter.opt.tencent': 'Tencent',
    'filter.opt.bytedance': 'ByteDance',
    'filter.opt.xunfei': 'iFlytek',

    'auth.loginTitle': 'ログイン',
    'auth.loginDesc': 'アカウントにログインしてすべての機能を利用',
    'auth.email': 'メールアドレス',
    'auth.password': 'パスワード',
    'auth.noAccount': 'アカウントをお持ちでないですか？',
    'auth.goRegister': '今すぐ登録',
    'auth.loginBtn': 'ログイン',
    'auth.loginFailed': 'ログインに失敗しました',
    'auth.loginSuccess': 'ログインしました',
    'auth.welcomeBack': 'おかえりなさい！',
    'auth.registerTitle': 'アカウント登録',
    'auth.registerDesc': 'アカウントを作成してAIツールをお気に入り登録・レビュー',
    'auth.confirmPassword': 'パスワード（確認）',
    'auth.registerBtn': '登録',
    'auth.haveAccount': 'すでにアカウントをお持ちですか？',
    'auth.goLogin': 'ログイン',
    'auth.pwdMismatch': 'パスワードが一致しません',
    'auth.pwdMismatchDesc': '2つのパスワードが同じか確認してください',
    'auth.pwdShort': 'パスワードが短すぎます',
    'auth.pwdShortDesc': 'パスワードは6文字以上必要です',
    'auth.registerFailed': '登録に失敗しました',
    'auth.registerSuccess': '登録が完了しました',
    'auth.welcome': 'ようこそ！',
    'detail.loginFirst': '先にログインしてください',
    'detail.favAdded': 'お気に入りに追加しました',
    'detail.favRemoved': 'お気に入りを解除しました',
    'detail.commentEmpty': 'コメントを入力してください',
    'detail.commentSuccess': 'コメントを投稿しました',
    'detail.commentFailed': 'コメントの投稿に失敗しました',
    'detail.notFound': 'ツールが見つかりません',
    'detail.backHome': 'ホームに戻る',
    'detail.hot': '人気',
    'detail.featured': '注目',
    'detail.reviews': '{count} 件のレビュー',
    'detail.views': '{count} 回閲覧',
    'detail.added': '{date} 掲載',
    'detail.visit': '公式サイトへ',
    'detail.favorited': 'お気に入り済み',
    'detail.favorite': 'お気に入り',
    'detail.details': '詳細紹介',
    'detail.quickInfo': '基本情報',
    'detail.website': '公式サイト',
    'detail.category': 'カテゴリ',
    'detail.viewCount': '閲覧数',
    'detail.times': '{count} 回',
    'detail.comments': 'レビュー ({count})',
    'detail.rating': '評価：',
    'detail.commentPlaceholder': '使用感を共有してください...',
    'detail.submitComment': 'コメントを投稿',
    'detail.loginToComment': 'ログインするとコメントできます',
    'detail.goLogin': 'ログインする',
    'detail.anonymous': '匿名ユーザー',
    'detail.noComments': 'まだコメントがありません。最初の一件を投稿しましょう',
    'profile.joined': '{date} に参加',
    'profile.favorites': 'お気に入り ({count})',
    'profile.comments': 'マイコメント ({count})',
    'profile.noFavorites': 'お気に入りのツールはありません',
    'profile.noComments': 'コメントはありません',
    'smart.badge': 'AIスマート推薦',
    'smart.title1': 'ニーズを入力すると、',
    'smart.title2': 'AIが最適なツールを提案',
    'smart.desc': 'どのAIツールを使うか迷っていますか？やりたいことを教えてください。{count} 件のツールからAIが最適なものを選びます',
    'smart.f1': '意図を理解',
    'smart.f2': '数秒で提案',
    'smart.f3': '高精度マッチング',
    'smart.placeholder': 'ニーズを入力してください。AIが最適なツールを提案します...\n例：AIでマーケティング文章と画像を生成したい',
    'smart.hint': 'Enterで送信、Shift + Enterで改行',
    'smart.analyzing': 'AIが分析中...',
    'smart.submit': 'スマート推薦',
    'smart.examples': '例を試してみましょう：',
    'smart.loading': 'AIがニーズを分析しています...',
    'smart.loadingDesc': '{count} 件のツールから最適な候補を選定中',
    'smart.found': '{count} 件の推薦が見つかりました',
    'smart.rec': 'おすすめ {index}',
    'smart.retry': '条件を入力し直す',
    'smart.noResult': '一致するツールが見つかりません。別の表現でお試しください',
    'smart.searchAgain': '再検索',
    'smart.emptyInput': 'ニーズを入力してください',
    'smart.error': '推薦サービスが一時的に利用できません。後ほどお試しください',
    'smart.ex1': 'ショート動画を作りたい。台本・ナレーション・編集をAIに手伝ってほしい',
    'smart.ex2': '無料のAI画像生成ツールを探しています（VPN不要が理想）',
    'smart.ex3': 'エンジニアです。開発効率を上げるAIツールはありますか？',
    'smart.ex4': 'ExcelデータをAIで処理してレポートを作りたい',
    'news.justNow': 'たった今',
    'oauth.loadFailed': '認可リクエストを読み込めません',
    'oauth.loading': '認可リクエストを読み込み中…',
    'oauth.connect': '{app} をあなたのアカウントに接続',
    'oauth.desc': '承認すると、{app} はあなたとしてツールデータとお気に入りにアクセスできます。',
    'oauth.approve': '承認する',
    'oauth.deny': '拒否',
    'oauth.thisApp': 'このアプリ',

    'category.ai-chat': 'AI対話',
    'category.ai-image': 'AI画像',
    'category.ai-video': 'AI動画',
    'category.ai-audio': 'AI音声',
    'category.ai-writing': 'AIライティング',
    'category.ai-code': 'コード生成',
    'category.ai-education': 'AI教育',
    'category.ai-music': 'AI音楽',
    'category.ai-health': 'AIヘルス',
    'category.ai-life': 'AI生活',
    'category.ai-finance': 'AI金融',
    'category.ai-business': 'AIビジネス',
    'category.ai-design': 'AIデザイン',
    'category.ai-architecture': 'AI建築',
    'category.ai-agent': 'AIエージェント',
    'category.ai-other': 'その他',
    'catdesc.ai-agent': "人気のAIエージェントと自動化エージェント",
    'catdesc.ai-audio': "音声合成、音楽生成、オーディオ処理",
    'catdesc.ai-business': "経営管理、マーケティング、データ分析",
    'catdesc.ai-chat': "質問応答・執筆・プログラミングに対応するAI対話アシスタント",
    'catdesc.ai-code': "コード生成、補完、プログラミング支援",
    'catdesc.ai-design': "UIデザイン、グラフィックデザイン、クリエイティブツール",
    'catdesc.ai-education': "スマート学習、オンライン教育、知識Q&A",
    'catdesc.ai-finance': "金融分析、投資アドバイス、資産管理ツール",
    'catdesc.ai-health': "健康管理、医療相談、フィットネス指導",
    'catdesc.ai-image': "AI画像の生成・編集ツール",
    'catdesc.ai-life': "日常生活アシスタントと効率化ツール",
    'catdesc.ai-music': "音楽制作、楽曲生成、編曲ツール",
    'catdesc.ai-video': "AI動画の生成・編集・エフェクト処理",
    'catdesc.ai-writing': "コピーライティング、コンテンツ生成、文章最適化",
  },
  ko: {
    'nav.explore': '탐색',
    'nav.smartSearch': '스마트 검색',
    'nav.login': '로그인',
    'nav.register': '회원가입',
    'nav.profile': '프로필',
    'nav.admin': '관리자',
    'nav.logout': '로그아웃',
    'search.placeholder': 'AI 도구 검색...',
    'brand.name': 'AI 내비',

    'hero.badge': '{count} 개의 엄선된 AI 도구',
    'hero.h1': 'AI 도구의 무한한 가능성을 탐색하세요',
    'hero.desc': '대화, 이미지, 영상, 오디오, 글쓰기, 코딩 등 다양한 분야의 우수한 AI 도구 모음',
    'hero.placeholder': '도구 이름, 기능 또는 카테고리 검색...',
    'hero.searchButton': '검색',
    'hero.smartCta': '무엇을 고를지 모르겠다면? AI 추천을 사용해 보세요',
    'hero.popular': '인기:',
    'hero.stats.tools': 'AI 도구',
    'hero.stats.categories': '카테고리',
    'hero.stats.daily': '매일 업데이트',

    'hot.badge': '인기 추천',
    'hot.title': '가장 인기 있는 AI 도구',
    'hot.desc': '평점이 높고 사용량이 많은 AI 도구를 엄선했습니다',
    'hot.prev': '이전',
    'hot.next': '다음',
    'hot.total': '총 {count} 개',
    'hot.empty': '현재 조건에 맞는 도구가 없습니다',

    'cat.badge': '전체 카테고리',
    'cat.title': '카테고리별 AI 도구 보기',
    'cat.desc': '대화, 이미지, 영상, 오디오, 글쓰기, 코딩 등',
    'cat.viewMore': '더 보기',
    'cat.emptyTools': '이 카테고리에는 아직 도구가 없습니다',
    'cat.noData': '카테고리 데이터가 없습니다',
    'cat.notFound': '카테고리를 찾을 수 없습니다',
    'cat.notFoundDesc': '링크가 올바른지 확인해 주세요',
    'cat.count': '총 {count} 개',
    'cat.emptyFilter': '조건에 맞는 도구가 없습니다. 다른 필터를 시도하세요',

    'oscar.badge': 'Oscar 랭킹',
    'oscar.title': 'AI 도구 Oscar 랭킹',
    'oscar.desc': '조회수, 평점, 리뷰 수를 종합해 카테고리별 Top 3를 선정',
    'oscar.viewAll': '전체 보기',
    'oscar.empty': '랭킹 데이터가 없습니다',

    'news.title': 'AI 뉴스',
    'news.live': '실시간',
    'news.empty': '뉴스가 없습니다',
    'news.more': '뉴스 더 보기',

    'card.hot': '인기',
    'card.featured': '⭐ 추천',

    'footer.tagline': '최고의 AI 도구를 찾아 생산성을 높이세요',
    'footer.categories': '카테고리',
    'footer.quickLinks': '바로가기',
    'footer.home': '홈',
    'footer.submit': '도구 제출',
    'footer.allCategories': '전체 카테고리',
    'footer.feedback': '피드백',
    'footer.contact': '연락처',

    'result.title': '검색 결과: ',
    'result.count': '총 {count} 개의 결과',
    'result.notFound': '관련 도구를 찾을 수 없습니다',
    'result.notFoundDesc': '다른 조건이나 키워드를 시도해 보세요',

    'explore.badge': '고급 필터',
    'explore.title': '탐색',
    'explore.titleAccent': 'AI 도구 라이브러리',
    'explore.desc': '{count} 개의 AI 도구에서 가장 알맞은 도구를 찾아보세요',
    'explore.placeholder': '이름, 설명 또는 태그 검색...',
    'explore.clear': '지우기',
    'explore.allCategories': '전체 카테고리',
    'explore.results': '검색 결과',
    'explore.count': '{count} 개',
    'explore.noMatch': '일치하는 도구가 없습니다',
    'explore.noMatchDesc': '필터나 검색어를 조정해 보세요',
    'explore.clearAll': '모든 필터 지우기',
    'explore.hotTags': '인기 태그',
    'filter.title': '스마트 필터',
    'filter.conditions': '{count}개 조건',
    'filter.found': '{count}개 찾음',
    'filter.filtered': '필터 적용됨',
    'filter.clearAll': '전체 지우기',
    'filter.collapse': '고급 필터 접기',
    'filter.expand': '고급 필터 펼치기 (카테고리·용도·플랫폼·제조사)',
    'filter.group.access': '접속',
    'filter.group.pricing': '가격',
    'filter.group.category': '카테고리',
    'filter.group.features': '특징',
    'filter.group.usecase': '활용 분야',
    'filter.group.platform': '플랫폼',
    'filter.group.provider': '제조사',
    'filter.opt.no-vpn': '직접 접속',
    'filter.opt.vpn-required': 'VPN 필요',
    'filter.opt.free': '완전 무료',
    'filter.opt.freemium': '무료 제공량',
    'filter.opt.paid': '유료',
    'filter.opt.chat': '대화',
    'filter.opt.image': '이미지',
    'filter.opt.video': '영상',
    'filter.opt.audio': '오디오',
    'filter.opt.music': '음악',
    'filter.opt.writing': '글쓰기',
    'filter.opt.code': '코딩',
    'filter.opt.opensource': '오픈소스',
    'filter.opt.chinese': '중국산',
    'filter.opt.chinese-friendly': '중국어 지원',
    'filter.opt.enterprise': '엔터프라이즈',
    'filter.opt.api': 'API',
    'filter.opt.multimodal': '멀티모달',
    'filter.opt.marketing': '마케팅',
    'filter.opt.education': '교육',
    'filter.opt.design': '디자인',
    'filter.opt.productivity': '생산성',
    'filter.opt.research': '리서치',
    'filter.opt.health': '헬스',
    'filter.opt.finance': '금융',
    'filter.opt.web': '웹',
    'filter.opt.mobile': '모바일',
    'filter.opt.plugin': '플러그인',
    'filter.opt.openai': 'OpenAI',
    'filter.opt.google': 'Google',
    'filter.opt.meta': 'Meta',
    'filter.opt.microsoft': 'Microsoft',
    'filter.opt.baidu': 'Baidu',
    'filter.opt.alibaba': 'Alibaba',
    'filter.opt.tencent': 'Tencent',
    'filter.opt.bytedance': 'ByteDance',
    'filter.opt.xunfei': 'iFlytek',

    'auth.loginTitle': '로그인',
    'auth.loginDesc': '계정에 로그인하고 모든 기능을 사용하세요',
    'auth.email': '이메일',
    'auth.password': '비밀번호',
    'auth.noAccount': '계정이 없으신가요?',
    'auth.goRegister': '지금 가입하기',
    'auth.loginBtn': '로그인',
    'auth.loginFailed': '로그인 실패',
    'auth.loginSuccess': '로그인 성공',
    'auth.welcomeBack': '다시 오신 것을 환영합니다!',
    'auth.registerTitle': '계정 만들기',
    'auth.registerDesc': '계정을 만들고 AI 도구를 저장하고 리뷰하세요',
    'auth.confirmPassword': '비밀번호 확인',
    'auth.registerBtn': '가입하기',
    'auth.haveAccount': '이미 계정이 있으신가요?',
    'auth.goLogin': '로그인',
    'auth.pwdMismatch': '비밀번호가 일치하지 않습니다',
    'auth.pwdMismatchDesc': '두 비밀번호가 동일한지 확인하세요',
    'auth.pwdShort': '비밀번호가 너무 짧습니다',
    'auth.pwdShortDesc': '비밀번호는 최소 6자 이상이어야 합니다',
    'auth.registerFailed': '가입 실패',
    'auth.registerSuccess': '가입 완료',
    'auth.welcome': '환영합니다!',
    'detail.loginFirst': '먼저 로그인해 주세요',
    'detail.favAdded': '즐겨찾기에 추가됨',
    'detail.favRemoved': '즐겨찾기 해제됨',
    'detail.commentEmpty': '댓글 내용을 입력하세요',
    'detail.commentSuccess': '댓글이 등록되었습니다',
    'detail.commentFailed': '댓글 등록 실패',
    'detail.notFound': '도구를 찾을 수 없습니다',
    'detail.backHome': '홈으로',
    'detail.hot': '인기',
    'detail.featured': '추천',
    'detail.reviews': '리뷰 {count}개',
    'detail.views': '조회 {count}회',
    'detail.added': '{date} 등록',
    'detail.visit': '공식 사이트',
    'detail.favorited': '저장됨',
    'detail.favorite': '저장',
    'detail.details': '상세 소개',
    'detail.quickInfo': '기본 정보',
    'detail.website': '공식 웹사이트',
    'detail.category': '카테고리',
    'detail.viewCount': '조회수',
    'detail.times': '{count}회',
    'detail.comments': '리뷰 ({count})',
    'detail.rating': '평점:',
    'detail.commentPlaceholder': '사용 경험을 공유해 주세요...',
    'detail.submitComment': '댓글 등록',
    'detail.loginToComment': '로그인하면 댓글을 남길 수 있습니다',
    'detail.goLogin': '로그인하기',
    'detail.anonymous': '익명 사용자',
    'detail.noComments': '아직 댓글이 없습니다. 첫 댓글을 남겨보세요',
    'profile.joined': '{date} 가입',
    'profile.favorites': '내 즐겨찾기 ({count})',
    'profile.comments': '내 댓글 ({count})',
    'profile.noFavorites': '저장한 도구가 없습니다',
    'profile.noComments': '댓글이 없습니다',
    'smart.badge': 'AI 스마트 추천',
    'smart.title1': '필요한 것을 설명하면',
    'smart.title2': 'AI가 추천해 드립니다',
    'smart.desc': '어떤 AI 도구를 써야 할지 모르겠나요? 하고 싶은 일을 알려주시면 {count}개 도구 중에서 골라 드립니다',
    'smart.f1': '의도 이해',
    'smart.f2': '즉시 추천',
    'smart.f3': '정확한 매칭',
    'smart.placeholder': '필요한 것을 설명하면 AI가 가장 알맞은 도구를 추천합니다...\n예: AI로 마케팅 문구와 이미지를 만들고 싶어요',
    'smart.hint': 'Enter로 전송, Shift + Enter로 줄바꿈',
    'smart.analyzing': 'AI 분석 중...',
    'smart.submit': '스마트 추천',
    'smart.examples': '이런 예시를 사용해 보세요:',
    'smart.loading': 'AI가 요청을 분석하고 있습니다...',
    'smart.loadingDesc': '{count}개 도구 중에서 최적의 결과를 찾는 중',
    'smart.found': '추천 {count}개를 찾았습니다',
    'smart.rec': '추천 {index}',
    'smart.retry': '다시 설명하기',
    'smart.noResult': '일치하는 도구를 찾지 못했습니다. 다른 방식으로 설명해 보세요',
    'smart.searchAgain': '다시 검색',
    'smart.emptyInput': '필요한 내용을 입력해 주세요',
    'smart.error': '추천 서비스를 일시적으로 사용할 수 없습니다. 나중에 다시 시도해 주세요',
    'smart.ex1': '숏폼 영상을 만들고 싶어요. 대본, 더빙, 편집을 AI가 도와줬으면 합니다',
    'smart.ex2': 'VPN 없이 쓸 수 있는 무료 AI 이미지 생성 도구를 찾아주세요',
    'smart.ex3': '개발자입니다. 코딩 생산성을 높여줄 AI 도구가 있을까요?',
    'smart.ex4': '엑셀 데이터를 처리하고 보고서를 만들어 줄 AI가 필요합니다',
    'news.justNow': '방금',
    'oauth.loadFailed': '승인 요청을 불러올 수 없습니다',
    'oauth.loading': '승인 요청을 불러오는 중…',
    'oauth.connect': '{app}을(를) 내 계정에 연결',
    'oauth.desc': '승인하면 {app}이(가) 내 계정으로 도구 데이터와 즐겨찾기에 접근할 수 있습니다.',
    'oauth.approve': '승인',
    'oauth.deny': '거부',
    'oauth.thisApp': '이 앱',

    'category.ai-chat': 'AI 대화',
    'category.ai-image': 'AI 이미지',
    'category.ai-video': 'AI 영상',
    'category.ai-audio': 'AI 오디오',
    'category.ai-writing': 'AI 글쓰기',
    'category.ai-code': '코드 생성',
    'category.ai-education': 'AI 교육',
    'category.ai-music': 'AI 음악',
    'category.ai-health': 'AI 헬스',
    'category.ai-life': 'AI 라이프',
    'category.ai-finance': 'AI 금융',
    'category.ai-business': 'AI 비즈니스',
    'category.ai-design': 'AI 디자인',
    'category.ai-architecture': 'AI 건축',
    'category.ai-agent': 'AI 에이전트',
    'category.ai-other': '기타',
    'catdesc.ai-agent': "인기 AI 에이전트 및 자동화 에이전트",
    'catdesc.ai-audio': "음성 합성, 음악 생성, 오디오 처리",
    'catdesc.ai-business': "경영 관리, 마케팅, 데이터 분석",
    'catdesc.ai-chat': "질의응답·글쓰기·코딩을 지원하는 AI 대화 어시스턴트",
    'catdesc.ai-code': "코드 생성, 자동 완성, 프로그래밍 도우미",
    'catdesc.ai-design': "UI 디자인, 그래픽 디자인, 크리에이티브 도구",
    'catdesc.ai-education': "스마트 학습, 온라인 교육, 지식 Q&A",
    'catdesc.ai-finance': "금융 분석, 투자 조언, 재테크 도구",
    'catdesc.ai-health': "건강 관리, 의료 상담, 피트니스 가이드",
    'catdesc.ai-image': "AI 이미지 생성 및 편집 도구",
    'catdesc.ai-life': "일상 생활 어시스턴트와 생산성 도구",
    'catdesc.ai-music': "음악 창작, 곡 생성, 편곡 도구",
    'catdesc.ai-video': "AI 영상 생성, 편집, 특수효과",
    'catdesc.ai-writing': "카피라이팅, 콘텐츠 생성, 텍스트 최적화",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'zh';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let value = translations[language][key] ?? translations.zh[key] ?? key;
    if (params) {
      for (const [k, v] of Object.entries(params)) {
        value = value.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
      }
    }
    return value;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

/** Localized category name by slug, falling back to the DB name (Chinese). */
export const useCategoryDescription = () => {
  const { t, language } = useLanguage();
  return (slug: string, fallback: string | null | undefined) => {
    if (language === 'zh') return fallback || '';
    const key = `catdesc.${slug}`;
    const value = t(key);
    return value === key ? (fallback || '') : value;
  };
};

export const useCategoryName = () => {
  const { t, language } = useLanguage();
  return (slug: string, fallback: string) => {
    if (language === 'zh') return fallback;
    const key = `category.${slug}`;
    const value = t(key);
    return value === key ? fallback : value;
  };
};
