// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@1.0.0";

// src/lib/mcp/tools/search-tools.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z } from "npm:zod@^4.5.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-tools.ts
var SELECT = "id,name,description,description_en,website_url,logo_url,tags,is_hot,is_featured,view_count,rating_avg,rating_count,category_id";
var search_tools_default = defineTool({
  name: "search_ai_tools",
  title: "Search AI tools",
  description: "Search the AI tool directory by keyword (name, description or tag), optionally filtered by category slug.",
  inputSchema: {
    query: z.string().trim().min(1).optional().describe("Keyword to search for."),
    category_slug: z.string().trim().optional().describe("Category slug, e.g. ai-chat."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max number of results.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category_slug, limit }) => {
    const supabase = supabaseAnon();
    let categoryId;
    if (category_slug) {
      const { data: cat, error: catError } = await supabase.from("categories").select("id").eq("slug", category_slug).maybeSingle();
      if (catError) return { content: [{ type: "text", text: catError.message }], isError: true };
      if (!cat) {
        return {
          content: [{ type: "text", text: `No category found with slug "${category_slug}".` }],
          isError: true
        };
      }
      categoryId = cat.id;
    }
    let request = supabase.from("ai_tools").select(SELECT);
    if (categoryId) request = request.eq("category_id", categoryId);
    if (query) {
      const safe = query.replace(/[%_,]/g, " ").trim();
      request = request.or(
        `name.ilike.%${safe}%,description.ilike.%${safe}%,description_en.ilike.%${safe}%`
      );
    }
    const { data, error } = await request.order("view_count", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tools: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-tool.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z2 } from "npm:zod@^4.5.4";
var get_tool_default = defineTool2({
  name: "get_ai_tool",
  title: "Get AI tool details",
  description: "Fetch the full details of one AI tool by its id or exact name.",
  inputSchema: {
    id: z2.string().uuid().optional().describe("Tool id (uuid)."),
    name: z2.string().trim().min(1).optional().describe("Exact tool name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, name }) => {
    if (!id && !name) {
      return { content: [{ type: "text", text: "Provide either `id` or `name`." }], isError: true };
    }
    const supabase = supabaseAnon();
    let request = supabase.from("ai_tools").select("*, categories(name,slug)");
    request = id ? request.eq("id", id) : request.eq("name", name);
    const { data, error } = await request.limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Tool not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { tool: data }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@1.0.0";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List all AI tool categories with their slug, icon and tool count ordering.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const { data, error } = await supabaseAnon().from("categories").select("id,name,slug,description,icon,display_order").order("display_order", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-favorites.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@1.0.0";
var list_favorites_default = defineTool4({
  name: "list_my_favorites",
  title: "List my favorite tools",
  description: "List the AI tools the signed-in user has favorited.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("favorites").select("id,created_at,ai_tools(id,name,description,website_url)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { favorites: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-favorite.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z3 } from "npm:zod@^4.5.4";
var add_favorite_default = defineTool5({
  name: "add_favorite",
  title: "Favorite an AI tool",
  description: "Add an AI tool to the signed-in user's favorites.",
  inputSchema: { tool_id: z3.string().uuid().describe("Id of the AI tool to favorite.") },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
  handler: async ({ tool_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("favorites").insert({ user_id: ctx.getUserId(), tool_id }).select("id,tool_id,created_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? {}, null, 2) }],
      structuredContent: { favorite: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/remove-favorite.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z4 } from "npm:zod@^4.5.4";
var remove_favorite_default = defineTool6({
  name: "remove_favorite",
  title: "Remove a favorite",
  description: "Remove an AI tool from the signed-in user's favorites.",
  inputSchema: { tool_id: z4.string().uuid().describe("Id of the AI tool to un-favorite.") },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true },
  handler: async ({ tool_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { error } = await supabaseForUser(ctx).from("favorites").delete().eq("user_id", ctx.getUserId()).eq("tool_id", tool_id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Removed tool ${tool_id} from favorites.` }],
      structuredContent: { removed: true, tool_id }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hegqjbtaqrckqixyesbq";
var mcp_default = defineMcp({
  name: "ai",
  title: "AI \u5B9D\u85CF\u6307\u5357",
  version: "0.1.0",
  instructions: "Tools for the AI \u5B9D\u85CF\u6307\u5357 directory of 4000+ AI tools. Use `search_ai_tools` and `list_categories` to browse, `get_ai_tool` for full details, and the favorite tools to manage the signed-in user's saved tools.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_tools_default, get_tool_default, list_categories_default, list_favorites_default, add_favorite_default, remove_favorite_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@1.0.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
